#!/usr/bin/env bash
#
# deploy.sh — stand up the coffee-ship DVA-C03 testing-and-deployment demo.
#
# This creates REAL, BILLABLE AWS resources (ECS Fargate + ALB + CodePipeline +
# CodeBuild + ECR + DynamoDB + SQS + AppConfig). Run it in a throwaway sandbox
# account and tear it down with ./destroy.sh when you are done.
#
# Region is pinned to ap-southeast-1 everywhere to match the CDK/SAM config.
set -euo pipefail

# --- Configuration ----------------------------------------------------------
export AWS_REGION="ap-southeast-1"
export AWS_DEFAULT_REGION="ap-southeast-1"

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# CloudFormation stack names (= CDK construct ids from infra/bin/coffee-ship.ts).
NETWORK_STACK="CoffeeShipNetworkData"
PIPELINE_STACK="CoffeeShipAppPipeline"

# Fixed resource names declared in the CDK stacks.
ECR_REPO="coffee-ship"
PIPELINE_NAME="coffee-ship"
SOURCE_KEY="source.zip"

echo "==> coffee-ship deploy (region: ${AWS_REGION})"

# --- Preflight ---------------------------------------------------------------
echo "==> [0/6] Checking prerequisites"
for bin in aws docker node npm python3 zip; do
  if ! command -v "$bin" >/dev/null 2>&1; then
    echo "ERROR: required tool '$bin' not found on PATH." >&2
    exit 1
  fi
done

ACCOUNT_ID="$(aws sts get-caller-identity --query Account --output text)"
echo "    Using AWS account ${ACCOUNT_ID} in ${AWS_REGION}"

# --- 1. CDK bootstrap --------------------------------------------------------
# One-time per account+region. Safe to re-run; it is idempotent.
echo "==> [1/6] Bootstrapping CDK environment (idempotent)"
(
  cd "${ROOT}/infra"
  npm install
  npx cdk bootstrap "aws://${ACCOUNT_ID}/${AWS_REGION}"
)

# --- 2a. Deploy the data/network stack FIRST (creates the ECR repo) ----------
# ORDERING MATTERS: both the test ECS service and the CODE_DEPLOY prod service
# reference 'coffee-ship:latest'. If we deployed the pipeline stack (which
# creates those services) before any image exists in ECR, the services could
# not pull an image and would never stabilize (ECS circuit breaker trips). So
# we deploy the network/data stack first (it is what the AppPipeline stack
# imports), THEN seed ECR, THEN deploy the pipeline stack whose services now
# find 'coffee-ship:latest' already present.
echo "==> [2/6] Deploying the data/network stack (${NETWORK_STACK}) — creates ECR"
(
  cd "${ROOT}/infra"
  CDK_DEFAULT_ACCOUNT="${ACCOUNT_ID}" CDK_DEFAULT_REGION="${AWS_REGION}" \
    npx cdk deploy "${NETWORK_STACK}" --require-approval never
)

# The ECR repository 'coffee-ship' is created by the network stack above, so it
# now exists and can be seeded before the pipeline stack's ECS services (which
# pull 'coffee-ship:latest') are created.

# --- 2b. Seed ECR with an initial image BEFORE the services are created ------
# Build for linux/amd64 explicitly: AWS Fargate runs X86_64 by default, and on
# Apple Silicon / arm64 hosts a plain 'docker build' produces an arm64 image
# that will NOT run on the X86_64 task (CannotPullImageManifest / exec format
# error). --platform pins the target architecture regardless of the build host.
echo "==> [3/6] Seeding ECR with an initial container image (linux/amd64)"
ECR_URI="${ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${ECR_REPO}"
aws ecr get-login-password --region "${AWS_REGION}" \
  | docker login --username AWS --password-stdin "${ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com"
docker build --platform linux/amd64 -t "${ECR_URI}:latest" "${ROOT}/container"
docker push "${ECR_URI}:latest"
echo "    Pushed ${ECR_URI}:latest (linux/amd64)"

# --- 2c. Deploy the pipeline/app stack (services now find :latest in ECR) ----
echo "==> [3b/6] Deploying the app/pipeline stack (${PIPELINE_STACK})"
(
  cd "${ROOT}/infra"
  CDK_DEFAULT_ACCOUNT="${ACCOUNT_ID}" CDK_DEFAULT_REGION="${AWS_REGION}" \
    npx cdk deploy "${PIPELINE_STACK}" --require-approval never
)

# --- 4. Package the container source and upload to the pipeline source bucket -
# The CodePipeline source is an S3 object 'source.zip' in a versioned bucket
# whose name is auto-generated by CDK, so we resolve it from the stack rather
# than hardcoding it. The zip must contain the container/ directory and
# container/buildspec.yml (the CodeBuild project reads container/buildspec.yml).
# source.zip also carries the React SPA source at container/frontend/ and the
# diagram at container/architecture.svg (local node_modules/ and dist/ are
# excluded below — the multi-stage image rebuilds the SPA fresh).
echo "==> [4/6] Packaging container source and triggering the pipeline"
SOURCE_BUCKET="$(aws cloudformation describe-stack-resources \
  --stack-name "${PIPELINE_STACK}" \
  --query "StackResources[?ResourceType=='AWS::S3::Bucket'].PhysicalResourceId | [0]" \
  --output text)"

if [[ -z "${SOURCE_BUCKET}" || "${SOURCE_BUCKET}" == "None" ]]; then
  echo "ERROR: could not resolve the pipeline source bucket from ${PIPELINE_STACK}." >&2
  exit 1
fi
echo "    Source bucket: ${SOURCE_BUCKET}"

TMP_ZIP="$(mktemp -t coffee-ship-source.XXXXXX).zip"
trap 'rm -f "${TMP_ZIP}"' EXIT
(
  cd "${ROOT}"
  # Include the container/ dir (app.py, Dockerfile, buildspec.yml,
  # frontend/ SPA source, architecture.svg) but EXCLUDE a developer's local
  # frontend/node_modules/ and frontend/dist/ — the multi-stage Dockerfile
  # rebuilds the SPA fresh inside the image.
  zip -r "${TMP_ZIP}" container -x '*.pyc' -x '*__pycache__*' -x '*/node_modules/*' -x '*/dist/*' >/dev/null
)
aws s3 cp "${TMP_ZIP}" "s3://${SOURCE_BUCKET}/${SOURCE_KEY}"
echo "    Uploaded s3://${SOURCE_BUCKET}/${SOURCE_KEY} (pipeline '${PIPELINE_NAME}' will start)"

# --- 5. Resolve the CloudFront URLs (the public entry points) ----------------
# Neither ALB is publicly reachable (each SG only admits the CloudFront prefix
# list), so the student-facing URLs are CloudFront, from the stack outputs.
# PROD = CloudFrontUrl (prod ALB origin); TEST = TestCloudFrontUrl (test ALB
# origin). The second distribution adds no S3 bucket, so the AWS::S3::Bucket
# | [0] source-bucket lookup above is unaffected.
echo "==> [5/6] Resolving the CloudFront URLs"
CLOUDFRONT_URL="$(aws cloudformation describe-stacks \
  --stack-name "${PIPELINE_STACK}" \
  --query "Stacks[0].Outputs[?OutputKey=='CloudFrontUrl'].OutputValue | [0]" \
  --output text 2>/dev/null || true)"
TEST_CLOUDFRONT_URL="$(aws cloudformation describe-stacks \
  --stack-name "${PIPELINE_STACK}" \
  --query "Stacks[0].Outputs[?OutputKey=='TestCloudFrontUrl'].OutputValue | [0]" \
  --output text 2>/dev/null || true)"

# --- 6. Resolve the SAM API endpoint (if the SAM app stack is deployed) ------
echo "==> [6/6] Resolving the API endpoint"
API_ENDPOINT="$(aws cloudformation describe-stacks \
  --stack-name coffee-ship-app \
  --query "Stacks[0].Outputs[?OutputKey=='OrdersApiEndpoint'].OutputValue | [0]" \
  --output text 2>/dev/null || true)"

# --- Summary -----------------------------------------------------------------
echo ""
echo "============================================================"
echo " coffee-ship demo deployed in ${AWS_REGION}"
echo "------------------------------------------------------------"
if [[ -n "${CLOUDFRONT_URL}" && "${CLOUDFRONT_URL}" != "None" ]]; then
  echo " CloudFront URL : ${CLOUDFRONT_URL}  (PROD — use this; the ALB is not public)"
else
  echo " CloudFront URL : (not available yet — distribution may still deploy)"
fi
if [[ -n "${TEST_CLOUDFRONT_URL}" && "${TEST_CLOUDFRONT_URL}" != "None" ]]; then
  echo " Test CloudFront : ${TEST_CLOUDFRONT_URL}  (TEST — verify here before approving prod)"
else
  echo " Test CloudFront : (not available yet — distribution may still deploy)"
fi
if [[ -n "${API_ENDPOINT}" && "${API_ENDPOINT}" != "None" ]]; then
  echo " API endpoint   : ${API_ENDPOINT}"
else
  echo " API endpoint   : (serverless path is separate; deploy the SAM app and"
  echo "                  re-check the 'coffee-ship-app' output 'OrdersApiEndpoint')"
fi
echo "------------------------------------------------------------"
echo " The container pipeline rebuilds container/ on every source.zip upload"
echo " (multi-stage image: it runs 'npm run build' for the SPA, then serves it"
echo " from the python runtime). It deploys to TWO environments: a rolling"
echo " EcsDeployAction to coffee-ship-test, then — after the manual approval —"
echo " a CodeDeploy blue/green canary to coffee-ship-prod. Edit"
echo " container/frontend/src/* or container/app.py, run ./demo-pipeline.sh,"
echo " verify on the Test CloudFront URL, approve, and watch the Coffee Shop"
echo " web page served through the PROD CloudFront URL change."
echo "------------------------------------------------------------"
echo " Remember to run ./destroy.sh when you are finished — this"
echo " stack costs real money per hour (Fargate + ALB + CloudFront + pipeline)."
echo "============================================================"
