#!/usr/bin/env bash
#
# deploy.sh — stand up the coffee-ship DVA-C03 testing-and-deployment demo.
#
# This creates REAL, BILLABLE AWS resources (ECS Fargate + ALB + CodePipeline +
# CodeBuild + ECR + DynamoDB + SQS + AppConfig). Run it in a throwaway sandbox
# account and tear it down with ./destroy.sh when you are done.
#
# Region is pinned to ap-southeast-1 everywhere to match the CDK/SAM config.
set -euo pipefail

# --- Configuration ----------------------------------------------------------
export AWS_REGION="ap-southeast-1"
export AWS_DEFAULT_REGION="ap-southeast-1"

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# CloudFormation stack names (= CDK construct ids from infra/bin/coffee-ship.ts).
NETWORK_STACK="CoffeeShipNetworkData"
PIPELINE_STACK="CoffeeShipAppPipeline"

# Fixed resource names declared in the CDK stacks.
ECR_REPO="coffee-ship"
PIPELINE_NAME="coffee-ship"
SOURCE_KEY="source.zip"

echo "==> coffee-ship deploy (region: ${AWS_REGION})"

# --- Preflight ---------------------------------------------------------------
echo "==> [0/6] Checking prerequisites"
for bin in aws docker node npm python3 zip; do
  if ! command -v "$bin" >/dev/null 2>&1; then
    echo "ERROR: required tool '$bin' not found on PATH." >&2
    exit 1
  fi
done

ACCOUNT_ID="$(aws sts get-caller-identity --query Account --output text)"
echo "    Using AWS account ${ACCOUNT_ID} in ${AWS_REGION}"

# --- 1. CDK bootstrap --------------------------------------------------------
# One-time per account+region. Safe to re-run; it is idempotent.
echo "==> [1/6] Bootstrapping CDK environment (idempotent)"
(
  cd "${ROOT}/infra"
  npm install
  npx cdk bootstrap "aws://${ACCOUNT_ID}/${AWS_REGION}"
)

# --- 2. Deploy the CDK infra + pipeline --------------------------------------
echo "==> [2/6] Deploying CDK stacks (${NETWORK_STACK}, ${PIPELINE_STACK})"
(
  cd "${ROOT}/infra"
  CDK_DEFAULT_ACCOUNT="${ACCOUNT_ID}" CDK_DEFAULT_REGION="${AWS_REGION}" \
    npx cdk deploy --all --require-approval never
)

# --- 3. Seed the ECR repo so the ECS service can start -----------------------
# Bootstrap: the ECS/Fargate service references 'coffee-ship:latest', but the
# ECR repo is empty right after 'cdk deploy', so the service cannot stabilize
# until an image exists. We seed ':latest' with a local build here so the
# service becomes healthy immediately; the pipeline (step 4) then owns all
# subsequent image builds and real ECS deploys.
echo "==> [3/6] Seeding ECR with an initial container image"
ECR_URI="${ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${ECR_REPO}"
aws ecr get-login-password --region "${AWS_REGION}" \
  | docker login --username AWS --password-stdin "${ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com"
docker build -t "${ECR_REPO}:latest" "${ROOT}/container"
docker tag "${ECR_REPO}:latest" "${ECR_URI}:latest"
docker push "${ECR_URI}:latest"
echo "    Pushed ${ECR_URI}:latest"

# --- 4. Package the container source and upload to the pipeline source bucket -
# The CodePipeline source is an S3 object 'source.zip' in a versioned bucket
# whose name is auto-generated by CDK, so we resolve it from the stack rather
# than hardcoding it. The zip must contain the container/ directory and
# container/buildspec.yml (the CodeBuild project reads container/buildspec.yml).
# source.zip also carries the React SPA source at container/frontend/ and the
# diagram at container/architecture.svg (local node_modules/ and dist/ are
# excluded below — the multi-stage image rebuilds the SPA fresh).
echo "==> [4/6] Packaging container source and triggering the pipeline"
SOURCE_BUCKET="$(aws cloudformation describe-stack-resources \
  --stack-name "${PIPELINE_STACK}" \
  --query "StackResources[?ResourceType=='AWS::S3::Bucket'].PhysicalResourceId | [0]" \
  --output text)"

if [[ -z "${SOURCE_BUCKET}" || "${SOURCE_BUCKET}" == "None" ]]; then
  echo "ERROR: could not resolve the pipeline source bucket from ${PIPELINE_STACK}." >&2
  exit 1
fi
echo "    Source bucket: ${SOURCE_BUCKET}"

TMP_ZIP="$(mktemp -t coffee-ship-source.XXXXXX).zip"
trap 'rm -f "${TMP_ZIP}"' EXIT
(
  cd "${ROOT}"
  # Include the container/ dir (app.py, Dockerfile, buildspec.yml,
  # frontend/ SPA source, architecture.svg) but EXCLUDE a developer's local
  # frontend/node_modules/ and frontend/dist/ — the multi-stage Dockerfile
  # rebuilds the SPA fresh inside the image.
  zip -r "${TMP_ZIP}" container -x '*.pyc' -x '*__pycache__*' -x '*/node_modules/*' -x '*/dist/*' >/dev/null
)
aws s3 cp "${TMP_ZIP}" "s3://${SOURCE_BUCKET}/${SOURCE_KEY}"
echo "    Uploaded s3://${SOURCE_BUCKET}/${SOURCE_KEY} (pipeline '${PIPELINE_NAME}' will start)"

# --- 5. Resolve the CloudFront URL (the public entry point) ------------------
# The ALB is NOT publicly reachable (its SG only admits the CloudFront prefix
# list), so the student-facing URL is CloudFront, from the stack output.
echo "==> [5/6] Resolving the CloudFront URL"
CLOUDFRONT_URL="$(aws cloudformation describe-stacks \
  --stack-name "${PIPELINE_STACK}" \
  --query "Stacks[0].Outputs[?OutputKey=='CloudFrontUrl'].OutputValue | [0]" \
  --output text 2>/dev/null || true)"

# --- 6. Resolve the SAM API endpoint (if the SAM app stack is deployed) ------
echo "==> [6/6] Resolving the API endpoint"
API_ENDPOINT="$(aws cloudformation describe-stacks \
  --stack-name coffee-ship-app \
  --query "Stacks[0].Outputs[?OutputKey=='OrdersApiEndpoint'].OutputValue | [0]" \
  --output text 2>/dev/null || true)"

# --- Summary -----------------------------------------------------------------
echo ""
echo "============================================================"
echo " coffee-ship demo deployed in ${AWS_REGION}"
echo "------------------------------------------------------------"
if [[ -n "${CLOUDFRONT_URL}" && "${CLOUDFRONT_URL}" != "None" ]]; then
  echo " CloudFront URL : ${CLOUDFRONT_URL}  (use this; the ALB is not public)"
else
  echo " CloudFront URL : (not available yet — distribution may still deploy)"
fi
if [[ -n "${API_ENDPOINT}" && "${API_ENDPOINT}" != "None" ]]; then
  echo " API endpoint   : ${API_ENDPOINT}"
else
  echo " API endpoint   : (serverless path is separate; deploy the SAM app and"
  echo "                  re-check the 'coffee-ship-app' output 'OrdersApiEndpoint')"
fi
echo "------------------------------------------------------------"
echo " The container pipeline rebuilds container/ on every source.zip upload"
echo " (multi-stage image: it runs 'npm run build' for the SPA, then serves it"
echo " from the python runtime) and rolls the ECS service via real ECS deploy"
echo " actions — edit container/frontend/src/* or bump APP_VERSION in"
echo " container/app.py, re-run the Act 4 upload, approve, and watch the"
echo " Coffee Ship web page served through CloudFront change."
echo "------------------------------------------------------------"
echo " Remember to run ./destroy.sh when you are finished — this"
echo " stack costs real money per hour (Fargate + ALB + CloudFront + pipeline)."
echo "============================================================"
