version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: coffeeshop
        LoadBalancerInfo:
          ContainerName: coffeeshop
          ContainerPort: 8080
